### ISSUE TITLE
Incomptibility with the Foliaath from Mowzie's mobs

### ISSUE THREAD

**Issue by ekiplier** [baguchan/OnlyLooking#2]
The Foliaath from Mowzie's mobs behaves differently from most mobs. It only comes out when an entity approaches.

It seems the new a.i. from Onlylooking breaks this mechanic and the Foliaath never comes out to attack entities. Maybe you could add a blacklist so pack makers can keep the default a.i. from certain mobs like the Foliaath.

I'm playing on MC 1.16.5 with the Forge loader, build 36.2.35.

**Comment by baguchi** [comment]
I'll add blacklist in next update
sorry for bother

**Comment by ekiplier** [comment]
I see you added the blacklist option in the last update. Thank you so much! :) Do you think you could make a similar update but for 1.16.5 though? I would really appreciate it because I want to add this mod to my modpack but I can't since it conflicts with mowzie's mobs... Nevertheless, thank you for answering and best of luck to you! ❤️
